wallpaper {
    monitor = eDP-1
    path = /home/neil/backgrounds/arch-mountains.png
    fit_mode = fill
}

wallpaper {
    monitor = DP-1
    path = /home/neil/backgrounds/arch-mountains.png
    fit_mode = fill
}

splash = false

